name: Deploy backend to Fly.io

on:
  push:
    branches: [main]
    paths:
      - "apps/backend/**"
      - ".github/workflows/fly-deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@v1
        with:
          version: latest

      - name: fly deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy \
            --config apps/backend/fly.toml \
            --remote-only \
            --dockerfile apps/backend/Dockerfile
